import Navbar from "./assets/components/NavBar.jsx"
import Posts from "./assets/components/posts.jsx"
import "./assets/main.css"

const data = [
  {
    name: "SynthWave Studio",
    id: '1',
    rating: 4.5,
    producer: "AudioGL",
    COO: "Japan",
    features: [['Advanced Wavetable Synthesis', 9], ['Granular Synthesis Engine', 8], ['MPE Support', 7]],
    price: 199,
    priceModel: "One-time purchase",
    FAQ: [['Does it support VST3?', 'Yes, SynthWave Studio is available as a VST3 and AU plugin.'], ['What are the system requirements?', 'We recommend at least 8GB of RAM and a modern quad-core CPU.']],
    chatCommunity: [['Discord', 'https://discord.gg/synthwave-studio']],
    tutorials: [['Exploring the Wavetable Editor', 'https://youtu.be/synthwave-wavetable']],
    courses: [['Sound Design with SynthWave Studio', 'https://www.adsrsounds.com/synthwave-studio-course']],
    tipsAndTricks: [['Creating Evolving Pads', 'https://blog.audiogl.com/evolving-pads']],
    worthiness: 'Best for:\n- Electronic Music Producers\n- Sound Designers\n- Film Composers',
    cons: ['High CPU usage on complex patches', 'Steep learning curve for beginners'],
    pros: ['Incredible sound quality', 'Deep synthesis capabilities', 'Regular updates'],
    category: "Audio Production",
    tags: ['Synthesizer', 'VST', 'Sound Design'],
    subCategory: 'Virtual Instrument',
    articles: [['The Art of Wavetable Synthesis', 'https://www.soundonsound.com/techniques/art-wavetable-synthesis']],
    communities: [['KVR Audio', 'https://www.kvraudio.com/forum/viewforum.php?f=1&t=123456']],
    communitySupport: 'Active',
    pluginsEcoSystem: 'N/A',
    integrations: ['Ableton Live', 'FL Studio', 'Logic Pro X'],
    Platforms: ['Windows', 'macOS'],
    thumbnail: 'https://placehold.co/400x400/E91E63/FFFFFF/png',
    pictures: ['https://pic1.com', 'pic2.com'],
    video: 'https://vid2.com',
    description: "A powerful and versatile software synthesizer for modern music production."
  },
  {
    name: "GameMaker Pro",
    id: '2',
    rating: 4.8,
    producer: "DevKit",
    COO: "USA",
    features: [['Drag-and-drop interface', 9], ['Built-in physics engine', 8], ['Cross-platform export', 9]],
    price: 99,
    priceModel: "Annual Subscription",
    FAQ: [['Can I create 3D games?', 'GameMaker Pro is primarily for 2D game development, but some 3D functionality is available.'], ['Is there a marketplace for assets?', 'Yes, the GameMaker Marketplace has a wide variety of sprites, sounds, and scripts.']],
    chatCommunity: [['Reddit', 'https://www.reddit.com/r/gamemaker/']],
    tutorials: [['Creating Your First Platformer', 'https://youtu.be/gamemaker-platformer']],
    courses: [['Game Development with GameMaker Pro', 'https://www.udemy.com/course/gamemaker-pro-development/']],
    tipsAndTricks: [['Optimizing Your Game for Mobile', 'https://help.yoyogames.com/hc/en-us/articles/360005142252-Optimising-Your-Game-For-Mobile']],
    worthiness: 'Best for:\n- Indie Game Developers\n- Hobbyists\n- Students',
    cons: ['Limited 3D capabilities', 'Subscription model may not be for everyone'],
    pros: ['Easy to learn', 'Powerful features for 2D games', 'Active community'],
    category: "Game Development",
    tags: ['Game Engine', '2D Games', 'Indie Games'],
    subCategory: 'Game Engine',
    articles: [['The Rise of Indie Games', 'https://www.ign.com/articles/the-rise-of-indie-games']],
    communities: [['GameMaker Community', 'https://forum.yoyogames.com/index.php']],
    communitySupport: 'Excellent',
    pluginsEcoSystem: 'Extensive marketplace',
    integrations: ['Steamworks', 'Google Play Games'],
    Platforms: ['Windows', 'macOS', 'Linux', 'iOS', 'Android'],
    thumbnail: 'https://placehold.co/400x400/9C27B0/FFFFFF/png',
    pictures: ['https://pic1.com', 'pic2.com'],
    video: 'https://vid2.com',
    description: "A user-friendly game engine for creating 2D games across multiple platforms."
  },
  {
    name: "PhotoForge",
    id: '3',
    rating: 4.7,
    producer: "PixelMagic",
    COO: "UK",
    features: [['Non-destructive editing', 9], ['Advanced color grading', 8], ['AI-powered sky replacement', 7]],
    price: 149,
    priceModel: "One-time purchase",
    FAQ: [['Does it support RAW files?', 'Yes, PhotoForge supports a wide range of RAW file formats.'], ['Can I use Photoshop plugins?', 'Some Photoshop plugins are compatible, but not all.']],
    chatCommunity: [['Facebook Group', 'https://www.facebook.com/groups/photoforge']],
    tutorials: [['Getting Started with PhotoForge', 'https://youtu.be/photoforge-basics']],
    courses: [['Mastering Photo Editing with PhotoForge', 'https://www.skillshare.com/classes/Mastering-Photo-Editing-with-PhotoForge/987654321']],
    tipsAndTricks: [['Advanced Masking Techniques', 'https://pixelmagic.com/blog/advanced-masking']],
    worthiness: 'Best for:\n- Photographers\n- Digital Artists\n- Hobbyists',
    cons: ['Steeper learning curve than some competitors', 'No mobile app'],
    pros: ['Powerful editing tools', 'One-time purchase', 'Excellent performance'],
    category: "Photography",
    tags: ['Photo Editor', 'Image Manipulation', 'Digital Art'],
    subCategory: 'Photo Editing',
    articles: [['The Importance of Post-Processing in Photography', 'https://petapixel.com/2023/01/15/the-importance-of-post-processing-in-photography/']],
    communities: [['500px', 'https://500px.com/groups/photoforge']],
    communitySupport: 'Good',
    pluginsEcoSystem: 'Growing library of presets and LUTs',
    integrations: ['Adobe Lightroom', 'Capture One'],
    Platforms: ['Windows', 'macOS'],
    thumbnail: 'https://placehold.co/400x400/673AB7/FFFFFF/png',
    pictures: ['https://pic1.com', 'pic2.com'],
    video: 'https://vid2.com',
    description: "A professional photo editor for photographers who demand the best in image quality and performance."
  },
  {
    name: "LiveStream Pro",
    id: '4',
    rating: 4.9,
    producer: "StreamGeeks",
    COO: "USA",
    features: [['Multi-camera switching', 9], ['Real-time graphics and overlays', 8], ['Integrated chat and alerts', 9]],
    price: 0,
    priceModel: "Freemium",
    FAQ: [['What streaming platforms are supported?', 'LiveStream Pro supports Twitch, YouTube, Facebook Live, and custom RTMP servers.'], ['Can I use it for professional broadcasts?', 'Yes, many professionals use LiveStream Pro for their broadcasts.']],
    chatCommunity: [['Discord', 'https://discord.gg/livestream-pro']],
    tutorials: [['Setting Up Your First Stream', 'https://youtu.be/livestream-pro-setup']],
    courses: [['The Ultimate Guide to Live Streaming', 'https://www.udemy.com/course/the-ultimate-guide-to-live-streaming/']],
    tipsAndTricks: [['Engaging Your Audience with Interactive Overlays', 'https://streamgeeks.com/blog/interactive-overlays']],
    worthiness: 'Best for:\n- Live Streamers\n- Content Creators\n- Gamers',
    cons: ['Some advanced features require a subscription', 'Can be resource-intensive'],
    pros: ['Free to get started', 'Powerful and flexible', 'Excellent community support'],
    category: "Streaming",
    tags: ['Live Streaming', 'Broadcasting', 'Content Creation'],
    subCategory: 'Streaming Software',
    articles: [['The Rise of the Creator Economy', 'https://www.forbes.com/sites/abdoriani/2021/07/13/the-rise-of-the-creator-economy/']],
    communities: [['Twitch Creator Camp', 'https://www.twitch.tv/creatorcamp']],
    communitySupport: 'Excellent',
    pluginsEcoSystem: 'Large app store with many extensions',
    integrations: ['Streamlabs', 'StreamElements', 'Discord'],
    Platforms: ['Windows', 'macOS'],
    thumbnail: 'https://placehold.co/400x400/3F51B5/FFFFFF/png',
    pictures: ['https://pic1.com', 'pic2.com'],
    video: 'https://vid2.com',
    description: "A powerful and easy-to-use live streaming software for gamers, artists, and content creators."
  },
{
    name: "GameMaker Pro",
    id: '89',
    rating: 4.8,
    producer: "DevKit",
    COO: "USA",
    features: [['Drag-and-drop interface', 9], ['Built-in physics engine', 8], ['Cross-platform export', 9]],
    price: 99,
    priceModel: "Annual Subscription",
    FAQ: [['Can I create 3D games?', 'GameMaker Pro is primarily for 2D game development, but some 3D functionality is available.'], ['Is there a marketplace for assets?', 'Yes, the GameMaker Marketplace has a wide variety of sprites, sounds, and scripts.']],
    chatCommunity: [['Reddit', 'https://www.reddit.com/r/gamemaker/']],
    tutorials: [['Creating Your First Platformer', 'https://youtu.be/gamemaker-platformer']],
    courses: [['Game Development with GameMaker Pro', 'https://www.udemy.com/course/gamemaker-pro-development/']],
    tipsAndTricks: [['Optimizing Your Game for Mobile', 'https://help.yoyogames.com/hc/en-us/articles/360005142252-Optimising-Your-Game-For-Mobile']],
    worthiness: 'Best for:\n- Indie Game Developers\n- Hobbyists\n- Students',
    cons: ['Limited 3D capabilities', 'Subscription model may not be for everyone'],
    pros: ['Easy to learn', 'Powerful features for 2D games', 'Active community'],
    category: "Game Development",
    tags: ['Game Engine', '2D Games', 'Indie Games'],
    subCategory: 'Game Engine',
    articles: [['The Rise of Indie Games', 'https://www.ign.com/articles/the-rise-of-indie-games']],
    communities: [['GameMaker Community', 'https://forum.yoyogames.com/index.php']],
    communitySupport: 'Excellent',
    pluginsEcoSystem: 'Extensive marketplace',
    integrations: ['Steamworks', 'Google Play Games'],
    Platforms: ['Windows', 'macOS', 'Linux', 'iOS', 'Android'],
    thumbnail: 'https://placehold.co/400x400/9C27B0/FFFFFF/png',
    pictures: ['https://pic1.com', 'pic2.com'],
    video: 'https://vid2.com',
    description: "A user-friendly game engine for creating 2D games across multiple platforms."
  },
{
    name: "GameMaker Pro",
    id: '99',
    rating: 4.8,
    producer: "DevKit",
    COO: "USA",
    features: [['Drag-and-drop interface', 9], ['Built-in physics engine', 8], ['Cross-platform export', 9]],
    price: 99,
    priceModel: "Annual Subscription",
    FAQ: [['Can I create 3D games?', 'GameMaker Pro is primarily for 2D game development, but some 3D functionality is available.'], ['Is there a marketplace for assets?', 'Yes, the GameMaker Marketplace has a wide variety of sprites, sounds, and scripts.']],
    chatCommunity: [['Reddit', 'https://www.reddit.com/r/gamemaker/']],
    tutorials: [['Creating Your First Platformer', 'https://youtu.be/gamemaker-platformer']],
    courses: [['Game Development with GameMaker Pro', 'https://www.udemy.com/course/gamemaker-pro-development/']],
    tipsAndTricks: [['Optimizing Your Game for Mobile', 'https://help.yoyogames.com/hc/en-us/articles/360005142252-Optimising-Your-Game-For-Mobile']],
    worthiness: 'Best for:\n- Indie Game Developers\n- Hobbyists\n- Students',
    cons: ['Limited 3D capabilities', 'Subscription model may not be for everyone'],
    pros: ['Easy to learn', 'Powerful features for 2D games', 'Active community'],
    category: "Game Development",
    tags: ['Game Engine', '2D Games', 'Indie Games'],
    subCategory: 'Game Engine',
    articles: [['The Rise of Indie Games', 'https://www.ign.com/articles/the-rise-of-indie-games']],
    communities: [['GameMaker Community', 'https://forum.yoyogames.com/index.php']],
    communitySupport: 'Excellent',
    pluginsEcoSystem: 'Extensive marketplace',
    integrations: ['Steamworks', 'Google Play Games'],
    Platforms: ['Windows', 'macOS', 'Linux', 'iOS', 'Android'],
    thumbnail: 'https://placehold.co/400x400/9C27B0/FFFFFF/png',
    pictures: ['https://pic1.com', 'pic2.com'],
    video: 'https://vid2.com',
    description: "A user-friendly game engine for creating 2D games across multiple platforms."
  },
{
    name: "GameMaker Pro",
    id: '109',
    rating: 4.8,
    producer: "DevKit",
    COO: "USA",
    features: [['Drag-and-drop interface', 9], ['Built-in physics engine', 8], ['Cross-platform export', 9]],
    price: 99,
    priceModel: "Annual Subscription",
    FAQ: [['Can I create 3D games?', 'GameMaker Pro is primarily for 2D game development, but some 3D functionality is available.'], ['Is there a marketplace for assets?', 'Yes, the GameMaker Marketplace has a wide variety of sprites, sounds, and scripts.']],
    chatCommunity: [['Reddit', 'https://www.reddit.com/r/gamemaker/']],
    tutorials: [['Creating Your First Platformer', 'https://youtu.be/gamemaker-platformer']],
    courses: [['Game Development with GameMaker Pro', 'https://www.udemy.com/course/gamemaker-pro-development/']],
    tipsAndTricks: [['Optimizing Your Game for Mobile', 'https://help.yoyogames.com/hc/en-us/articles/360005142252-Optimising-Your-Game-For-Mobile']],
    worthiness: 'Best for:\n- Indie Game Developers\n- Hobbyists\n- Students',
    cons: ['Limited 3D capabilities', 'Subscription model may not be for everyone'],
    pros: ['Easy to learn', 'Powerful features for 2D games', 'Active community'],
    category: "Game Development",
    tags: ['Game Engine', '2D Games', 'Indie Games'],
    subCategory: 'Game Engine',
    articles: [['The Rise of Indie Games', 'https://www.ign.com/articles/the-rise-of-indie-games']],
    communities: [['GameMaker Community', 'https://forum.yoyogames.com/index.php']],
    communitySupport: 'Excellent',
    pluginsEcoSystem: 'Extensive marketplace',
    integrations: ['Steamworks', 'Google Play Games'],
    Platforms: ['Windows', 'macOS', 'Linux', 'iOS', 'Android'],
    thumbnail: 'https://placehold.co/400x400/9C27B0/FFFFFF/png',
    pictures: ['https://pic1.com', 'pic2.com'],
    video: 'https://vid2.com',
    description: "A user-friendly game engine for creating 2D games across multiple platforms."
  },
{
    name: "GameMaker Pro",
    id: '1000',
    rating: 4.8,
    producer: "DevKit",
    COO: "USA",
    features: [['Drag-and-drop interface', 9], ['Built-in physics engine', 8], ['Cross-platform export', 9]],
    price: 99,
    priceModel: "Annual Subscription",
    FAQ: [['Can I create 3D games?', 'GameMaker Pro is primarily for 2D game development, but some 3D functionality is available.'], ['Is there a marketplace for assets?', 'Yes, the GameMaker Marketplace has a wide variety of sprites, sounds, and scripts.']],
    chatCommunity: [['Reddit', 'https://www.reddit.com/r/gamemaker/']],
    tutorials: [['Creating Your First Platformer', 'https://youtu.be/gamemaker-platformer']],
    courses: [['Game Development with GameMaker Pro', 'https://www.udemy.com/course/gamemaker-pro-development/']],
    tipsAndTricks: [['Optimizing Your Game for Mobile', 'https://help.yoyogames.com/hc/en-us/articles/360005142252-Optimising-Your-Game-For-Mobile']],
    worthiness: 'Best for:\n- Indie Game Developers\n- Hobbyists\n- Students',
    cons: ['Limited 3D capabilities', 'Subscription model may not be for everyone'],
    pros: ['Easy to learn', 'Powerful features for 2D games', 'Active community'],
    category: "Game Development",
    tags: ['Game Engine', '2D Games', 'Indie Games'],
    subCategory: 'Game Engine',
    articles: [['The Rise of Indie Games', 'https://www.ign.com/articles/the-rise-of-indie-games']],
    communities: [['GameMaker Community', 'https://forum.yoyogames.com/index.php']],
    communitySupport: 'Excellent',
    pluginsEcoSystem: 'Extensive marketplace',
    integrations: ['Steamworks', 'Google Play Games'],
    Platforms: ['Windows', 'macOS', 'Linux', 'iOS', 'Android'],
    thumbnail: 'https://placehold.co/400x400/9C27B0/FFFFFF/png',
    pictures: ['https://pic1.com', 'pic2.com'],
    video: 'https://vid2.com',
    description: "A user-friendly game engine for creating 2D games across multiple platforms."
  },
{
    name: "GameMaker Pro",
    id: '104',
    rating: 4.8,
    producer: "DevKit",
    COO: "USA",
    features: [['Drag-and-drop interface', 9], ['Built-in physics engine', 8], ['Cross-platform export', 9]],
    price: 99,
    priceModel: "Annual Subscription",
    FAQ: [['Can I create 3D games?', 'GameMaker Pro is primarily for 2D game development, but some 3D functionality is available.'], ['Is there a marketplace for assets?', 'Yes, the GameMaker Marketplace has a wide variety of sprites, sounds, and scripts.']],
    chatCommunity: [['Reddit', 'https://www.reddit.com/r/gamemaker/']],
    tutorials: [['Creating Your First Platformer', 'https://youtu.be/gamemaker-platformer']],
    courses: [['Game Development with GameMaker Pro', 'https://www.udemy.com/course/gamemaker-pro-development/']],
    tipsAndTricks: [['Optimizing Your Game for Mobile', 'https://help.yoyogames.com/hc/en-us/articles/360005142252-Optimising-Your-Game-For-Mobile']],
    worthiness: 'Best for:\n- Indie Game Developers\n- Hobbyists\n- Students',
    cons: ['Limited 3D capabilities', 'Subscription model may not be for everyone'],
    pros: ['Easy to learn', 'Powerful features for 2D games', 'Active community'],
    category: "Game Development",
    tags: ['Game Engine', '2D Games', 'Indie Games'],
    subCategory: 'Game Engine',
    articles: [['The Rise of Indie Games', 'https://www.ign.com/articles/the-rise-of-indie-games']],
    communities: [['GameMaker Community', 'https://forum.yoyogames.com/index.php']],
    communitySupport: 'Excellent',
    pluginsEcoSystem: 'Extensive marketplace',
    integrations: ['Steamworks', 'Google Play Games'],
    Platforms: ['Windows', 'macOS', 'Linux', 'iOS', 'Android'],
    thumbnail: 'https://placehold.co/400x400/9C27B0/FFFFFF/png',
    pictures: ['https://pic1.com', 'pic2.com'],
    video: 'https://vid2.com',
    description: "A user-friendly game engine for creating 2D games across multiple platforms."
  }
]

function App() {
  const categories = ["Audio Production", "Game Development", "Photography", "Streaming"];
  const price = ["Free", "Freemium", "One-time purchase", "Subscription"];
  const rating = ["1", "2", "3", "4", "5"];
  const easeOfUse = ["Beginner", "Intermediate", "Advanced"];
  const standard = ["Web", "Desktop", "Mobile"];

  return (
    <div className="bg-gray-900 min-h-screen">
      <Navbar 
        categories={categories}
        price={price}
        rating={rating}
        easeOfUse={easeOfUse}
        standard={standard}
      />
      <div className="container w-full flex m-auto">
        <Posts data={data} />
      </div>
    </div>
  )
}

export default App
